AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  DatabaseUrl:
    Type: String
    Description: "The URL of the database"
  DatabaseName:
    Type: String
    Description: "The name of the database"
  DatabaseAlleventsCollectionName:
    Type: String
    Description: "The name of the Allevents collection"
  DatabaseLogCollectionName:
    Type: String
    Description: "The name of the Request Log collection"
  RecorderListUrl:
    Type: String
    Description: "Complete URL for RecorderId List"
  EventsApiUrl:
    Type: String
    Description: "Complete URL for Events List"
  ApiKey:
    Type: String
    Description: "The API KEY to access both RecorderId and Events"
  DifferenceBetweenDate:
    Type: String
    Description: "The Date Range"
  S3BucketName:
    Type: String
    Description: "S3 bucket name"
  AuthUsername:
    Type: String
    Description: "User Name for login"
  AuthPassword:
    Type: String
    Description: "Password for login"
  JwtSecret:
    Type: String
    Description: "JWT Secret value"
  JwtExpireMinutes:
    Type: String
    Description: "Token expiry period"
  Environment:
    Type: String
    Description: "Deployment environment"
#   EnableVPC:
#     Type: String
#     AllowedValues: ["true", "false"]
#     Default: "false"
#   SecurityGroupId:
#     Type: String
#     Description: "The security group id to attach with Vpc Configuration"
#     Default: "sg-0ad266cdcd20c6447"
#   VpcSubnet1:
#     Type: String
#     Description: "The subnet id to attach with Vpc Configuration"
#     Default: "subnet-05ad12c710538763e"
#   VpcSubnet2:
#     Type: String
#     Description: "The subnet id to attach with Vpc Configuration"
#     Default: "subnet-02c61e0b5521c071b"
#   VpcSubnet3:
#     Type: String
#     Description: "The subnet id to attach with Vpc Configuration"
#     Default: "subnet-0ebeb24684d96dc0d"

# Conditions:
#   ShouldEnableVPC: !Equals [!Ref EnableVPC, "true"]

Resources:
  EventsRetrievalApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default

  EventsRetrievalXirgoKp2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: "device-data-report.handler"
      Runtime: python3.12
      CodeUri: ./
      MemorySize: 256
      Timeout: 900
      # VpcConfig: !If
      #   - ShouldEnableVPC
      #   - Ipv6AllowedForDualStack: true
      #     SecurityGroupIds:
      #       - !Ref SecurityGroupId
      #     SubnetIds:
      #       - !Ref VpcSubnet1
      #       - !Ref VpcSubnet2
      #       - !Ref VpcSubnet3
      #   - !Ref AWS::NoValue
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          DATABASE_NAME: !Ref DatabaseName
          DATABASE_ALLEVENTS_COLLECTION_NAME: !Ref DatabaseAlleventsCollectionName
          DATABASE_LOG_COLL_NAME: !Ref DatabaseLogCollectionName
          RECORDER_LIST_URL: !Ref RecorderListUrl
          EVENTS_API_URL: !Ref EventsApiUrl
          DIFFERENCE_BETWEEN_DATE: !Ref DifferenceBetweenDate
          API_KEY: !Ref ApiKey
          S3_BUCKET_NAME: !Ref S3BucketName
          AUTH_USERNAME: !Ref AuthUsername
          AUTH_PASSWORD: !Ref AuthPassword
          JWT_SECRET: !Ref JwtSecret
          JWT_EXPIRE_MINUTES: !Ref JwtExpireMinutes
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref EventsRetrievalApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "URL for the API"
    Value: !Sub "https://${EventsRetrievalApi}.execute-api.${AWS::Region}.amazonaws.com/"
